:: remove o executavel final e os arquivos das pastas LST e OBJ
del %lstFolder%\main.lst
del %lstFolder%\data.lst
del %lstFolder%\teclado.lst
del %lstFolder%\line.lst
del %lstFolder%\plot_xy.lst
del %lstFolder%\menu.lst
del %lstFolder%\rect.lst
del %objFolder%\main.obj
del %objFolder%\data.obj
del %objFolder%\teclado.obj
del %objFolder%\line.obj
del %objFolder%\plot_xy.obj
del %objFolder%\menu.obj
del %objFolder%\rect.obj
del %projName%.EXE
cls
